# Generated by Django 6.0.1 on 2026-01-15 19:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')])),
                ('currency', models.CharField(db_index=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('bank_details', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('CREATED', 'created'), ('PENDING', 'pending'), ('READY', 'ready'), ('GIVEN', 'given'), ('CANCELLED', 'cancelled')], db_index=True, default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='payouts_pay_search__8092c6_gin')],
            },
        ),
    ]
